<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <UseWindowsForms>true</UseWindowsForms>
    <DefineConstants>WINDOWS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Binance.Net" Version="13.3.0" />
    <PackageReference Include="DuckDB.NET.Data" Version="1.5.5" />
    <PackageReference Include="DuckDB.NET.Data.Full" Version="1.5.5" />
    <PackageReference Include="ScottPlot" Version="5.1.59" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <PackageReference Include="ScottPlot.WinForms" Version="5.1.59" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net8.0-windows'">
    <Compile Remove="Form1.cs" />
    <Compile Remove="Form1.Designer.cs" />
    <EmbeddedResource Remove="Form1.resx" />
  </ItemGroup>

</Project>